config/routes.rb
Rails.application.routes.draw do
  resources :usuarios
  devise_for :users
  resources :productos
  resources :articulos do
    resources :comentarios
end
  get 'bienvenido/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'bienvenido#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/articulo.rb
class Articulo < ApplicationRecord
  has_many :comentarios, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 5 }
end

app/models/comentario.rb
class Comentario < ApplicationRecord
  belongs_to :articulo
end

app/models/producto.rb
class Producto < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/usuario.rb
class Usuario < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articulos_controller.rb
class ArticulosController < ApplicationController
http_basic_authenticate_with name: "nasugo", password: "JEPA", except: [:index, :show]
  def index
      @articulos = Articulo.all
  end
  def show
    #id le dice a rails que esta ruta espera un parámetro: id, que en nuestro caso será el id del artículo.

      @articulo = Articulo.find(params[:id])
    end

  def new
     @articulo = Articulo.new
  end

  def edit
    session[:articuloID] = params[:id]
    @articulo = Articulo.find(params[:id])
  end

  def create
  # cada modelo de Rails se puede inicializar con sus respectivos atributos,
  # que se asignan automáticamente a las columnas de la base de datos respectivas.
  # En la primera línea hacemos justamente eso (recuerde que params [: article] contiene los atributos
  # que nos interesan). Entonces, @ article.save es responsable de guardar el modelo en la base de datos.
  #Finalmente, redirigimos al usuario a la acción de mostrar, que definiremos más adelante.
    @articulo = Articulo.new(articulo_params)
# retorna un boolean indicando si fue creado o no.

      if @articulo.save
        flash[:notice] = "Articulo creado correctamente"
         redirect_to @articulo
       else
         flash[:error] = "No pudo crear articulo"
         render 'new'
       end
  end

  def update
  #  @articulo = Articulo.find(params[:id])
    @articulo = Articulo.find(session[:articuloID])
    session.delete(:articuloID)
    if @articulo.update(articulo_params)
      redirect_to @articulo
    else
      render 'edit'
    end
  end

  def destroy
    @articulo = Articulo.find(params[:id])
    @articulo.destroy

    redirect_to articulos_path
  end

  private
    def articulo_params
      params.require(:articulo).permit(:title, :text)
    end

end

app/controllers/bienvenido_controller.rb
class BienvenidoController < ApplicationController
  def index
  end
end

app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
http_basic_authenticate_with name: "nasugo", password: "JEPA", only: :destroy

  def create
  #  Estamos obteniedo el articulo Xid
   @articulo = Articulo.find(params[:articulo_id])
   #Estamos creando el comentario dentro de articulo
   @comentario = @articulo.comentarios.create(comentario_params)
   #redirigimos a la vista show del articulo
   redirect_to articulo_path(@articulo)
 end

 def destroy
     @articulo = Articulo.find(params[:articulo_id])
     @comentario = @articulo.comentarios.find(params[:id])
     @comentario.destroy
     redirect_to articulo_path(@articulo)
   end

 private
   def comentario_params
     params.require(:comentario).permit(:nombre, :cuerpo)
   end
end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  before_action :set_producto, only: [:show, :edit, :update, :destroy]

  # GET /productos
  # GET /productos.json
  def index
    @productos = Producto.all
  end

  # GET /productos/1
  # GET /productos/1.json
  def show
  end

  # GET /productos/new
  def new
    @producto = Producto.new
  end

  # GET /productos/1/edit
  def edit
  end

  # POST /productos
  # POST /productos.json
  def create
    @producto = Producto.new(producto_params)

    respond_to do |format|
      if @producto.save
        format.html { redirect_to @producto, notice: 'Producto was successfully created.' }
        format.json { render :show, status: :created, location: @producto }
      else
        format.html { render :new }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /productos/1
  # PATCH/PUT /productos/1.json
  def update
    respond_to do |format|
      if @producto.update(producto_params)
        format.html { redirect_to @producto, notice: 'Producto was successfully updated.' }
        format.json { render :show, status: :ok, location: @producto }
      else
        format.html { render :edit }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productos/1
  # DELETE /productos/1.json
  def destroy
    @producto.destroy
    respond_to do |format|
      format.html { redirect_to productos_url, notice: 'Producto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_producto
      @producto = Producto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def producto_params
      params.require(:producto).permit(:nombre, :precio, :descripcion, :disponible)
    end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: [:show, :edit, :update, :destroy]

  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        UsuarioMailer.with(usuario: @usuario).bienvenidos_email.deliver_now
        format.html { redirect_to @usuario, notice: 'Usuario was successfully created.' }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: 'Usuario was successfully updated.' }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: 'Usuario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usuario_params
      params.require(:usuario).permit(:nombre, :email, :login)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articulos_helper.rb
module ArticulosHelper
end

app/helpers/bienvenido_helper.rb
module BienvenidoHelper
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/articulos/_form.html.erb
<%= form_with model: @articulo, local: true do |form| %>

  <% if @articulo.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@articulo.errors.count, "error") %> prohibido
        Este artículo Contiene:
      </h2>
      <ul>
        <% @articulo.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

app/views/articulos/edit.html.erb
<h1>Edición Articulo</h1>

<%= render 'form' %>

<%= link_to 'Regresar', articulos_path %>

app/views/articulos/index.html.erb
<h1>Lista de articulos</h1>

<table>
  <tr>
    <th>Titulo</th>
    <th>Texto</th>
    <th></th>
  </tr>

  <% @articulos.each do |articulo| %>
    <tr>
      <td><%= articulo.title %></td>
      <td><%= articulo.text %></td>
      <td><%= link_to 'Ver', articulo_path(articulo) %></td>
      <td><%= link_to 'Editar', edit_articulo_path(articulo) %></td>
      <td><%= link_to 'Eliminar', articulo_path(articulo),
              method: :delete,
              data: { confirm: 'Confirma eliminación?' } %></td>
    </tr>
  <% end %>
</table>
  <%= link_to 'Crear', :action=>"new", :controller=>"articulos"%>

app/views/articulos/new.html.erb
<h1>Nuevo  Articulo</h1>
<!--Para crear un formulario dentro de esta plantilla, usará un generador de formularios.
 generador de formularios primario para Rails se proporciona mediante un método auxiliar llamado form_with.
-->
<%= render 'form' %>
<% if flash[:notice] %>
<div class="notice"> <%= flash[:notice] %> </div>
<% end %>
<% if flash[:error] %>
<div class="error"> <%= flash[:error] %> </div>
<% end %>
<%= link_to 'REgresar', articulos_path %>

app/views/articulos/show.html.erb
<p>
  <strong>Titulo:</strong>
  <%= @articulo.title %>
</p>

<p>
  <strong>Texto:</strong>
  <%= @articulo.text %>
</p>

<h2>Comentarios</h2>
<%= render @articulo.comentarios %>

<h2>Agregar comentario:</h2>
<%= render 'comentarios/form' %>

<% if flash[:notice] %>
<div class="notice"> <%= flash[:notice] %> </div>
<% end %>
<% if flash[:error] %>
<div class="error"> <%= flash[:error] %> </div>
<% end %>
<%= link_to 'Editar', edit_articulo_path(@articulo) %> |
<%= link_to 'REgresar', articulos_path %>

app/views/bienvenido/index.html.erb
<p class="navbar-text pull-right">
  <%= link_to 'Mi blog', controller: 'articulos' %>
</p>

<p id="notice"><%= notice %></p>

app/views/comentarios/_comentario.html.erb
<p>
  <strong>Comenta:</strong>
  <%= comentario.nombre %>
</p>

<p>
  <strong>Comentario:</strong>
  <%= comentario.cuerpo %>
</p>
<p>
  <%= link_to 'Eliminar Comentario', [comentario.articulo, comentario],
               method: :delete,
               data: { confirm: '¿Estas seguro de eliminar el comentario?' } %>
</p>

app/views/comentarios/_form.html.erb
<%= form_with(model: [ @articulo, @articulo.comentarios.build ], local: true) do |form| %>
  <p>
    <%= form.label :nombre %><br>
    <%= form.text_field :nombre %>
  </p>
  <p>
    <%= form.label :cuerpo %><br>
    <%= form.text_area :cuerpo %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <% if current_user %>
     Usuario con el email:  <strong><%= current_user.email %></strong>.
    <%= link_to 'Editar perfil', edit_user_registration_path, :class => 'navbar-link' %> |
    <%= link_to 'Logout', destroy_user_session_path, method: :delete %> <br>
    <%= yield %>
    <% else %>
        <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
        <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
        <% if controller.controller_name == "sessions" || controller.controller_name =="registrations" %>
         <%= yield %>
       <% end %>
    <% end %>
  </body>
</html>

app/views/productos/_form.html.erb
<%= form_with(model: producto, local: true) do |form| %>
  <% if producto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(producto.errors.count, "error") %> prohibited this producto from being saved:</h2>

      <ul>
      <% producto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :precio %>
    <%= form.text_field :precio %>
  </div>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_area :descripcion %>
  </div>

  <div class="field">
    <%= form.label :disponible %>
    <%= form.check_box :disponible %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/productos/edit.html.erb
<h1>Editing Producto</h1>

<%= render 'form', producto: @producto %>

<%= link_to 'Show', @producto %> |
<%= link_to 'Back', productos_path %>

app/views/productos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Productos</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Precio</th>
      <th>Descripcion</th>
      <th>Disponible</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @productos.each do |producto| %>
      <tr>
        <td><%= producto.nombre %></td>
        <td><%= producto.precio %></td>
        <td><%= producto.descripcion %></td>
        <td><%= producto.disponible %></td>
        <td><%= link_to 'Show', producto %></td>
        <td><%= link_to 'Edit', edit_producto_path(producto) %></td>
        <td><%= link_to 'Destroy', producto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Producto', new_producto_path %>

app/views/productos/new.html.erb
<h1>New Producto</h1>

<%= render 'form', producto: @producto %>

<%= link_to 'Back', productos_path %>

app/views/productos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @producto.nombre %>
</p>

<p>
  <strong>Precio:</strong>
  <%= @producto.precio %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @producto.descripcion %>
</p>

<p>
  <strong>Disponible:</strong>
  <%= @producto.disponible %>
</p>

<%= link_to 'Edit', edit_producto_path(@producto) %> |
<%= link_to 'Back', productos_path %>

app/views/usuarios/_form.html.erb
<%= form_with(model: usuario, local: true) do |form| %>
  <% if usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
      <% usuario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :login %>
    <%= form.text_field :login %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/usuarios/edit.html.erb
<h1>Editing Usuario</h1>

<%= render 'form', usuario: @usuario %>

<%= link_to 'Show', @usuario %> |
<%= link_to 'Back', usuarios_path %>

app/views/usuarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Usuarios</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Email</th>
      <th>Login</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= usuario.nombre %></td>
        <td><%= usuario.email %></td>
        <td><%= usuario.login %></td>
        <td><%= link_to 'Show', usuario %></td>
        <td><%= link_to 'Edit', edit_usuario_path(usuario) %></td>
        <td><%= link_to 'Destroy', usuario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Usuario', new_usuario_path %>

app/views/usuarios/new.html.erb
<h1>New Usuario</h1>

<%= render 'form', usuario: @usuario %>

<%= link_to 'Back', usuarios_path %>

app/views/usuarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @usuario.nombre %>
</p>

<p>
  <strong>Email:</strong>
  <%= @usuario.email %>
</p>

<p>
  <strong>Login:</strong>
  <%= @usuario.login %>
</p>

<%= link_to 'Edit', edit_usuario_path(@usuario) %> |
<%= link_to 'Back', usuarios_path %>